### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by Andro-Meta** [Chan-0312/ComfyUI-IPAnimate#1]
I seem to get this error when I try to run this node past 112 images. The speed and detail from these images is nice compared to running it through animatediff!

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\00000_COMFY\ComfyUI_Updated_Steerable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\00000_COMFY\ComfyUI_Updated_Steerable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\00000_COMFY\ComfyUI_Updated_Steerable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\00000_COMFY\ComfyUI_Updated_Steerable\ComfyUI\custom_nodes\ComfyUI-IPAnimate\main.py", line 109, in apply
    assert index < len(flow_image_indexs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by Andro-Meta** [comment]
Also, there's a new tiled ipadapter update that I think might make this workflow better for images that aren't 1:1 ratio

https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#tiled-ipadapter
